import type { SkillNode, NodeId } from './skilltree.js';

// ---------------------------------------------------------------------------
// Extraction branch
// ---------------------------------------------------------------------------

export const MINING_NOTABLES: SkillNode[] = [
  {
    id: 'mining.notable.deepVein' as NodeId,
    subPath: 'mining',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'mineYieldBonusMul' },
    description: 'Deep Vein Surveying — +20% mine yield per Mine',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'mining.notable.heliumSeep' as NodeId,
    subPath: 'mining',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'mineRareTrickleMul' },
    description: 'Helium Seep Detection — +15% helium-3 trickle from Mines',
  },
  {
    id: 'mining.notable.efficientDrills' as NodeId,
    subPath: 'mining',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'powerConsumptionMul', reduce: true },
    description: 'Efficient Drill Motors — -10% power draw for extraction buildings',
  },
  {
    id: 'mining.notable.blastOptimization' as NodeId,
    subPath: 'mining',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Blast Optimization — +25% extraction recipe rate',
  },
];

export const FORESTRY_NOTABLES: SkillNode[] = [
  {
    id: 'forestry.notable.selectiveHarvest' as NodeId,
    subPath: 'forestry',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'loggerYieldBonusMul' },
    description: 'Selective Harvest — +20% logger yield per Logger',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'forestry.notable.exoticInoculation' as NodeId,
    subPath: 'forestry',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'loggerExoticTrickleMul' },
    description: 'Exotic Inoculation — +15% exotic lumber trickle from Loggers',
  },
  {
    id: 'forestry.notable.clearcutCoordination' as NodeId,
    subPath: 'forestry',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Clearcut Coordination — +10% extraction recipe rate',
  },
  {
    id: 'forestry.notable.silvicultureHub' as NodeId,
    subPath: 'forestry',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Silviculture Hub — +25% extraction recipe rate',
    aura: { radius: 2, bonus: 0.12 },
  },
];

export const DRILLING_NOTABLES: SkillNode[] = [
  {
    id: 'drilling.notable.pressurizedRecovery' as NodeId,
    subPath: 'drilling',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'mineYieldBonusMul' },
    description: 'Pressurized Recovery — +20% well yield per Drill',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'drilling.notable.reservoirMapping' as NodeId,
    subPath: 'drilling',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Reservoir Mapping — +15% extraction recipe rate',
  },
  {
    id: 'drilling.notable.subseaTanks' as NodeId,
    subPath: 'drilling',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'storageCategoryCapMul', category: 'liquid_gas' },
    description: 'Subsea Tanks — +10% liquid/gas storage cap',
  },
  {
    id: 'drilling.notable.deepBore' as NodeId,
    subPath: 'drilling',
    depth: 6,
    cost: 7,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Deep Bore Architecture — +25% extraction recipe rate',
  },
];

export const ROBOTICS_NOTABLES: SkillNode[] = [
  {
    id: 'robotics.notable.swarmAssembly' as NodeId,
    subPath: 'robotics',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'constructionTimeMul' },
    description: 'Swarm Assembly — +20% construction speed (÷1.20 time)',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'robotics.notable.parallelFoundries' as NodeId,
    subPath: 'robotics',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'parallelBuildCapAdd' },
    description: 'Parallel Foundries — +1 concurrent build slot',
  },
  {
    id: 'robotics.notable.droneOptics' as NodeId,
    subPath: 'robotics',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'droneScanRadiusMul' },
    description: 'Drone Optics Refit — +10% drone scan radius',
  },
  {
    id: 'robotics.notable.biofuelCell' as NodeId,
    subPath: 'robotics',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'droneFuelEfficiencyMul' },
    description: 'Biofuel Cell Upgrade — +25% drone fuel efficiency',
  },
];

// ---------------------------------------------------------------------------
// Refinement branch
// ---------------------------------------------------------------------------

export const SMELTING_NOTABLES: SkillNode[] = [
  {
    id: 'smelting.notable.inductionArc' as NodeId,
    subPath: 'smelting',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'recipeRateMul', category: 'smelting' },
    description: 'Induction Arc Furnace — +20% smelting recipe rate',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'smelting.notable.heatRecapture' as NodeId,
    subPath: 'smelting',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'powerConsumptionMul', reduce: true },
    description: 'Heat Recapture Loop — -10% smelter power draw',
  },
  {
    id: 'smelting.notable.refractoryLining' as NodeId,
    subPath: 'smelting',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'maintenanceThresholdMul' },
    description: 'Refractory Lining — +15% maintenance threshold',
  },
  {
    id: 'smelting.notable.alloyTolerance' as NodeId,
    subPath: 'smelting',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'smelting' },
    description: 'Alloy Tolerance Protocol — +25% smelting recipe rate',
  },
];

export const CHEMISTRY_NOTABLES: SkillNode[] = [
  {
    id: 'chemistry.notable.catalyticCracking' as NodeId,
    subPath: 'chemistry',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'recipeRateMul', category: 'chemistry' },
    description: 'Catalytic Cracking — +20% chemistry recipe rate',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'chemistry.notable.pressurizedReactors' as NodeId,
    subPath: 'chemistry',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'storageCategoryCapMul', category: 'liquid_gas' },
    description: 'Pressurized Reactors — +10% liquid/gas storage cap',
  },
  {
    id: 'chemistry.notable.greenChemistry' as NodeId,
    subPath: 'chemistry',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'powerConsumptionMul', reduce: true },
    description: 'Green Chemistry — -15% chemistry building power draw',
  },
  {
    id: 'chemistry.notable.polymerMatrix' as NodeId,
    subPath: 'chemistry',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'chemistry' },
    description: 'Polymer Matrix Reactor — +25% chemistry recipe rate',
  },
];

export const ELECTRONICS_NOTABLES: SkillNode[] = [
  {
    id: 'electronics.notable.cleanRoom' as NodeId,
    subPath: 'electronics',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'recipeRateMul', category: 'electronics' },
    description: 'Clean Room Protocol — +20% electronics recipe rate',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'electronics.notable.lowPowerDesign' as NodeId,
    subPath: 'electronics',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'powerConsumptionMul', reduce: true },
    description: 'Low-Power Chip Design — -10% electronics building power draw',
  },
  {
    id: 'electronics.notable.satBandwidth' as NodeId,
    subPath: 'electronics',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'satBufferCapMul' },
    description: 'Satellite Bandwidth Expansion — +15% store-and-forward buffer',
  },
  {
    id: 'electronics.notable.quantumEtching' as NodeId,
    subPath: 'electronics',
    depth: 6,
    cost: 7,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'electronics' },
    description: 'Quantum Etching — +25% electronics recipe rate',
  },
];

export const POWER_SYSTEMS_NOTABLES: SkillNode[] = [
  {
    id: 'power_systems.notable.turbineStaging' as NodeId,
    subPath: 'power_systems',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'powerProductionMul' },
    description: 'Turbine Staging — +20% power production',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'power_systems.notable.smartGrid' as NodeId,
    subPath: 'power_systems',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'powerConsumptionMul', reduce: true },
    description: 'Smart Grid Balancing — -10% island-wide power consumption',
  },
  {
    id: 'power_systems.notable.xpTelemetry' as NodeId,
    subPath: 'power_systems',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'xpGainMul', category: 'power' },
    description: 'Telemetry Logging — +15% XP from power-category recipes',
  },
  {
    id: 'power_systems.notable.fusionPilot' as NodeId,
    subPath: 'power_systems',
    depth: 6,
    cost: 8,
    magnitude: 0.25,
    effect: { kind: 'powerProductionMul' },
    description: 'Fusion Pilot Plant — +25% power production',
    aura: { radius: 2, bonus: 0.15 },
  },
];

// ---------------------------------------------------------------------------
// Logistics branch
// ---------------------------------------------------------------------------

export const STORAGE_NOTABLES: SkillNode[] = [
  {
    id: 'storage.notable.verticalSilo' as NodeId,
    subPath: 'storage',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'storageCapMul' },
    description: 'Vertical Silo Expansion — +20% all storage caps',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'storage.notable.vaultClimate' as NodeId,
    subPath: 'storage',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'storageCategoryCapMul', category: 'rare' },
    description: 'Vault Climate Control — +10% rare-material storage cap',
  },
  {
    id: 'storage.notable.componentRacks' as NodeId,
    subPath: 'storage',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'storageCategoryCapMul', category: 'components' },
    description: 'Component Rack Automation — +15% component storage cap',
  },
  {
    id: 'storage.notable.predictiveMaintenance' as NodeId,
    subPath: 'storage',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'maintenanceThresholdMul' },
    description: 'Predictive Maintenance AI — +25% maintenance threshold',
  },
];

export const TRANSPORT_NOTABLES: SkillNode[] = [
  {
    id: 'transport.notable.heavyHaul' as NodeId,
    subPath: 'transport',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'routeCapacityMul' },
    description: 'Heavy Haul Certification — +20% route batch capacity',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'transport.notable.jetStream' as NodeId,
    subPath: 'transport',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'airshipRangeMul' },
    description: 'Jet Stream Routing — +10% airship route range',
  },
  {
    id: 'transport.notable.droneSwarmLogistics' as NodeId,
    subPath: 'transport',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'droneFuelEfficiencyMul' },
    description: 'Drone Swarm Logistics — +15% drone fuel efficiency',
  },
  {
    id: 'transport.notable.supplyHub' as NodeId,
    subPath: 'transport',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'routeCapacityMul' },
    description: 'Regional Supply Hub — +25% route batch capacity',
    aura: { radius: 2, bonus: 0.12 },
  },
];

export const NETWORK_NOTABLES: SkillNode[] = [
  {
    id: 'network.notable.relayAmplifier' as NodeId,
    subPath: 'network',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'commRangeMul' },
    description: 'Relay Amplifier — +20% comm range',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'network.notable.teleporterCoil' as NodeId,
    subPath: 'network',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'teleporterEfficiencyMul' },
    description: 'Teleporter Coil Tuning — -10% teleporter fuel cost',
  },
  {
    id: 'network.notable.scannerUplink' as NodeId,
    subPath: 'network',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'scannerCoverageMul' },
    description: 'Scanner Uplink — +15% scanner coverage radius',
  },
  {
    id: 'network.notable.meshNetwork' as NodeId,
    subPath: 'network',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'commRangeMul' },
    description: 'Mesh Network Topology — +25% comm range',
  },
];

export const PATRONAGE_NOTABLES: SkillNode[] = [
  {
    id: 'patronage.notable.sponsorContracts' as NodeId,
    subPath: 'patronage',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Sponsor Contracts — +20% extraction recipe rate',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'patronage.notable.curatorVaults' as NodeId,
    subPath: 'patronage',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'storageCategoryCapMul', category: 'rare' },
    description: 'Curator Vaults — +10% rare-material storage cap',
  },
  {
    id: 'patronage.notable.diplomaticChannels' as NodeId,
    subPath: 'patronage',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'commRangeMul' },
    description: 'Diplomatic Channels — +15% comm range',
  },
  {
    id: 'patronage.notable.endowmentFund' as NodeId,
    subPath: 'patronage',
    depth: 6,
    cost: 7,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Endowment Fund — +25% extraction recipe rate',
  },
];

// ---------------------------------------------------------------------------
// Ocean branch
// ---------------------------------------------------------------------------

export const AQUACULTURE_NOTABLES: SkillNode[] = [
  {
    id: 'aquaculture.notable.kelpTowers' as NodeId,
    subPath: 'aquaculture',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'mineYieldBonusMul' },
    description: 'Kelp Tower Farms — +20% aquaculture yield',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'aquaculture.notable.brineConcentration' as NodeId,
    subPath: 'aquaculture',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Brine Concentration — +10% extraction recipe rate',
  },
  {
    id: 'aquaculture.notable.dryStorageBarges' as NodeId,
    subPath: 'aquaculture',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'storageCategoryCapMul', category: 'dry_goods' },
    description: 'Dry-Storage Barges — +15% dry-goods storage cap',
  },
  {
    id: 'aquaculture.notable.maricultureGrid' as NodeId,
    subPath: 'aquaculture',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'extraction' },
    description: 'Mariculture Grid — +25% extraction recipe rate',
  },
];

export const HYDROPROCESSING_NOTABLES: SkillNode[] = [
  {
    id: 'hydroprocessing.notable.desalinationCascade' as NodeId,
    subPath: 'hydroprocessing',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'recipeRateMul', category: 'chemistry' },
    description: 'Desalination Cascade — +20% chemistry recipe rate',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'hydroprocessing.notable.osmoticPump' as NodeId,
    subPath: 'hydroprocessing',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'powerConsumptionMul', reduce: true },
    description: 'Osmotic Pump Retrofit — -10% hydroprocessing power draw',
  },
  {
    id: 'hydroprocessing.notable.floatingTanks' as NodeId,
    subPath: 'hydroprocessing',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'storageCapMul' },
    description: 'Floating Buffer Tanks — +15% all storage caps',
  },
  {
    id: 'hydroprocessing.notable.membraneBreakthrough' as NodeId,
    subPath: 'hydroprocessing',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'recipeRateMul', category: 'chemistry' },
    description: 'Membrane Breakthrough — +25% chemistry recipe rate',
  },
];

export const SUBMARINE_NOTABLES: SkillNode[] = [
  {
    id: 'submarine.notable.pressureHull' as NodeId,
    subPath: 'submarine',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'routeCapacityMul' },
    description: 'Pressure-Hull Cargo — +20% submarine route capacity',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'submarine.notable.thermalGradient' as NodeId,
    subPath: 'submarine',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'powerProductionMul' },
    description: 'Thermal-Gradient Harvest — +10% power production',
  },
  {
    id: 'submarine.notable.sonarMapping' as NodeId,
    subPath: 'submarine',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'airshipRangeMul' },
    description: 'Sonar-Mapped Airways — +15% airship route range',
  },
  {
    id: 'submarine.notable.deepFreighter' as NodeId,
    subPath: 'submarine',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'routeCapacityMul' },
    description: 'Deep Freighter Convoy — +25% submarine route capacity',
  },
];

export const OCEANOGRAPHY_NOTABLES: SkillNode[] = [
  {
    id: 'oceanography.notable.buoyArray' as NodeId,
    subPath: 'oceanography',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'scannerCoverageMul' },
    description: 'Buoy Sensor Array — +20% scanner coverage',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'oceanography.notable.seafloorCable' as NodeId,
    subPath: 'oceanography',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'commRangeMul' },
    description: 'Seafloor Cable Relay — +10% comm range',
  },
  {
    id: 'oceanography.notable.aerialSurvey' as NodeId,
    subPath: 'oceanography',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'droneScanRadiusMul' },
    description: 'Aerial Ocean Survey — +15% drone scan radius',
  },
  {
    id: 'oceanography.notable.tidalPrediction' as NodeId,
    subPath: 'oceanography',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'scannerCoverageMul' },
    description: 'Tidal Prediction Net — +25% scanner coverage',
  },
];

// ---------------------------------------------------------------------------
// Orbital branch
// ---------------------------------------------------------------------------

export const LAUNCH_NOTABLES: SkillNode[] = [
  {
    id: 'launch.notable.padRedundancy' as NodeId,
    subPath: 'launch',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'launchSuccessAdditive' },
    description: 'Pad Redundancy — +20% additive launch success (capped at 99%)',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'launch.notable.blastDeflector' as NodeId,
    subPath: 'launch',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'padExplosionReduceMul' },
    description: 'Blast Deflector — ÷1.10 pad-explosion likelihood',
  },
  {
    id: 'launch.notable.satDatapool' as NodeId,
    subPath: 'launch',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'satBufferCapMul' },
    description: 'Satellite Datapool — +15% store-and-forward buffer',
  },
  {
    id: 'launch.notable.reserveTanks' as NodeId,
    subPath: 'launch',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'satFuelReserveMul' },
    description: 'Reserve Tank Array — +25% onboard fuel reserve',
  },
];

export const COMMUNICATION_NOTABLES: SkillNode[] = [
  {
    id: 'communication.notable.groundStationHub' as NodeId,
    subPath: 'communication',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'commRangeMul' },
    description: 'Ground Station Hub — +20% comm range',
    aura: { radius: 2, bonus: 0.12 },
  },
  {
    id: 'communication.notable.packetBurst' as NodeId,
    subPath: 'communication',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'satBufferCapMul' },
    description: 'Packet Burst Mode — +10% store-and-forward buffer',
  },
  {
    id: 'communication.notable.scannerOverlap' as NodeId,
    subPath: 'communication',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'scannerCoverageMul' },
    description: 'Scanner Overlap Protocol — +15% scanner coverage',
  },
  {
    id: 'communication.notable.relayConstellation' as NodeId,
    subPath: 'communication',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'commRangeMul' },
    description: 'Relay Constellation — +25% comm range',
  },
];

export const DISCOVERY_NOTABLES: SkillNode[] = [
  {
    id: 'discovery.notable.dwellOptimization' as NodeId,
    subPath: 'discovery',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'scannerDwellRateMul' },
    description: 'Dwell Optimization — +20% scanner dwell-ramp rate',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'discovery.notable.wideAperture' as NodeId,
    subPath: 'discovery',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'scannerCoverageMul' },
    description: 'Wide Aperture Lens — +10% scanner coverage',
  },
  {
    id: 'discovery.notable.droneAstrogeology' as NodeId,
    subPath: 'discovery',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'droneScanRadiusMul' },
    description: 'Astrogeology Drones — +15% drone scan radius',
  },
  {
    id: 'discovery.notable.deepField' as NodeId,
    subPath: 'discovery',
    depth: 6,
    cost: 7,
    magnitude: 0.25,
    effect: { kind: 'scannerCoverageMul' },
    description: 'Deep Field Survey — +25% scanner coverage',
  },
];

export const RESILIENCE_NOTABLES: SkillNode[] = [
  {
    id: 'resilience.notable.orbitalShields' as NodeId,
    subPath: 'resilience',
    depth: 4,
    cost: 4,
    magnitude: 0.20,
    effect: { kind: 'debrisProtectionMul' },
    description: 'Orbital Shielding — +20% debris protection',
    aura: { radius: 1, bonus: 0.10 },
  },
  {
    id: 'resilience.notable.redundantSystems' as NodeId,
    subPath: 'resilience',
    depth: 3,
    cost: 3,
    magnitude: 0.10,
    effect: { kind: 'repairDroneReliabilityMul' },
    description: 'Redundant Repair Systems — ÷1.10 repair-drone failure rate',
  },
  {
    id: 'resilience.notable.hardenedInfrastructure' as NodeId,
    subPath: 'resilience',
    depth: 5,
    cost: 5,
    magnitude: 0.15,
    effect: { kind: 'maintenanceThresholdMul' },
    description: 'Hardened Infrastructure — +15% maintenance threshold',
  },
  {
    id: 'resilience.notable.debrisWake' as NodeId,
    subPath: 'resilience',
    depth: 6,
    cost: 6,
    magnitude: 0.25,
    effect: { kind: 'debrisProtectionMul' },
    description: 'Debris Wake Dispersal — +25% debris protection',
    aura: { radius: 2, bonus: 0.12 },
  },
];

// ---------------------------------------------------------------------------
// Combined catalog
// ---------------------------------------------------------------------------

export const NOTABLES: SkillNode[] = [
  ...MINING_NOTABLES,
  ...FORESTRY_NOTABLES,
  ...DRILLING_NOTABLES,
  ...ROBOTICS_NOTABLES,
  ...SMELTING_NOTABLES,
  ...CHEMISTRY_NOTABLES,
  ...ELECTRONICS_NOTABLES,
  ...POWER_SYSTEMS_NOTABLES,
  ...STORAGE_NOTABLES,
  ...TRANSPORT_NOTABLES,
  ...NETWORK_NOTABLES,
  ...PATRONAGE_NOTABLES,
  ...AQUACULTURE_NOTABLES,
  ...HYDROPROCESSING_NOTABLES,
  ...SUBMARINE_NOTABLES,
  ...OCEANOGRAPHY_NOTABLES,
  ...LAUNCH_NOTABLES,
  ...COMMUNICATION_NOTABLES,
  ...DISCOVERY_NOTABLES,
  ...RESILIENCE_NOTABLES,
];
